package pe.fridays.niubizapp

import java.lang.StringBuilder

fun getStringToPrintTest(): String {
    val builder = StringBuilder()
    builder.appendRowCenter("FRANQUICIAS ALIMENTARIAS SA")
    builder.addLineBreak()
    builder.appendRowCenter("TIENDA: OVALO MONITOR")
    builder.addLineBreak()
    builder.appendRowCenter("AV. LAS PALMERAS MZA. B1 LOTE. 14 URB. CAMACHO LIMA - LIMA - LA MOLINA")
    builder.addLineBreak()
    builder.appendRowCenter("RUC 20298674611")
    builder.addLineBreak()
    builder.appendRowCenter("00577/064 11/09/20 14:18 1750")
    builder.addLineBreak()
    builder.appendRowCenter("104319368588 Christian E. Mercado Justo")
    builder.addLineBreak()
    builder.appendTwoWordsInRow("TICKET NRO:", "F001-0001")
    builder.addDoubleLineBreak()
    builder.appendTwoWordsInRow("CHICKEN FINGER", "49.95")
    builder.addLineBreak()
    builder.appendTwoWordsInRow("DOBLE MOJITO", "54.98")
    builder.addLineBreak()
    builder.appendTwoWordsInRow("KIDS ALFREDO PASTA", "19.95")
    builder.addLineBreak()
    builder.appendTwoWordsInRow("PROMO NIUBIZ", "59.98")
    builder.addLineBreak()
    builder.appendTwoWordsInRow("BURGER BACON", "139.90")
    builder.addLineBreak()
    builder.appendTwoWordsInRow("COCA COLA VASO", "0.25")
    builder.addDoubleLineBreak()
    builder.appendTwoWordsInRow("SUBTOTAL", "S/ 325.01")
    builder.addLineBreak()
    builder.appendTwoWordsInRow("OP. GRAVADAS", "275.43")
    builder.addLineBreak()
    builder.appendTwoWordsInRow("I.G.V.(18%)", "49.58")
    builder.addLineBreak()
    builder.appendTwoWordsInRow("TOTAL A PAGAR", "S/ 325.01")
    builder.addLineBreak()
    builder.appendRowLeft("SON: TRESCIENTOS VEINTICINCO Y 1/100")
    builder.addLineBreak()
    builder.appendRowLeft("SOLES")
    builder.addDoubleLineBreak()
    builder.appendTwoWordsInRow("TARJ NIUBIZ 525435******1263", "325.01")
    builder.addDoubleLineBreak()
    builder.appendTwoWordsInRow("MONTO", "325.01")
    builder.addLineBreak()
    builder.appendTwoWordsInRow("PRIMER VENCIMIENTO", "05/11/2020")
    builder.addLineBreak()
    builder.appendTwoWordsInRow("VALOR CUOTA (S/)", "183.21")
    builder.addLineBreak()
    builder.appendRowLeft("CUOTAS: 2")
    builder.addDoubleLineBreak()
    builder.appendRowCenter("GRACIAS POR SU COMPRA")
    builder.addDoubleLineBreak()
    builder.appendRowCenter("=======================================")
    return builder.toString()
}